language: ruby
rvm:
  - "2.0.0"
notifications:
  email:
    recipients:
      - "michael@psu.edu"
      - "cam156@psu.edu"
      - "dmc186@psu.edu"
    on_success: "change"
    on_failure: "always"
  irc:
    channels:
      - "irc.freenode.org#scholarsphere"
      - "irc.freenode.org#projecthydra"
    template:
      - "%{repository}//%{branch}@%{commit} by %{author}: %{message} - %{build_url}"
